service: facebook-echoing-bot-demo

provider:
  name: aws
  runtime: nodejs8.10

# Lambda functions
functions:
  fbverify:
    handler: handler.fbVerify
    events:
      - http:
          path: fbhook
          method: GET
          integration: lambda
  fbmessages:
    handler: handler.fbMessages
    events:
      - http:
          path: fbhook
          method: POST
          integration: lambda
